version: '3.4'

services:

  tempo:
    image: grafana/tempo:1.4.1
    command: [ "-config.file=/etc/tempo-local.yaml" ]
    ports:
      - 9411:9411 # zipkin
      - 3100:3100 # tempo
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - 14250:14250 # jaeger ingest
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo-local.yaml
      - ./tempo-data:/tmp/tempo
    networks:
      - webnet

  tempo-query:
    image: grafana/tempo-query:1.4.1
    command: [ "--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml" ]
    volumes:
      - ./tempo/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui
    networks:
      - webnet
    depends_on:
      - tempo

  db:
    image: postgres:12.10
    restart: on-failure
    ports:
      - 5432:5432 
    environment:
      POSTGRES_DB: "evax"
      POSTGRES_PASSWORD: "mdp"
      POSTGRES_USER: "shatha"
    volumes:
      - ./postgres:/var/lib/postgres
    networks:
      - webnet
      
  evax-backend:
    container_name: evax-backend
    build: ./Backend
    environment:
      - "spring.datasource.url=jdbc:postgresql://db:5432/evax"
      - "spring.datasource.password=mdp"
      - "spring.datasource.username=shatha"
      - "spring.sleuth.otel.exporter.zipkin.endpoint=http://tempo:9411"
      - "spring.zipkin.baseUrl=http://tempo:9411"
    ports:
      - 8888:8888
    networks:
      - webnet
    depends_on:
      - db

  evax-frontend:
    container_name: evax-frontend
    build: ./frontend
    ports:
      - 3333:80
    networks:
      - webnet

networks:
  webnet:
